name: Conviso Platform AST
on:
 workflow_dispatch:
 #push:
 #  branches: [ main, develop ]
 #pull_request:
 #  branches: [ main, develop ]

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli:1.12.4-rc.0
      env:
        FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}
        FLOW_API_URL: 'https://app.convisoappsec.com'
    steps:
    - uses: actions/checkout@v3
  
    - name: AST
      run: conviso ast run
